# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
org.gradle.caching=true
org.gradle.parallel=false
hermesEnabled=true

MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=R@njeet22
MYAPP_UPLOAD_KEY_PASSWORD=R@njeet22

# 🔥 Add these (important)
kotlin.compiler.jvmTarget=17
android.overridePathCheck=true
