org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true    
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
org.gradle.caching=true
org.gradle.parallel=false
hermesEnabled=true

# Kotlin + Java 17
kotlin.compiler.jvmTarget=17
kotlin.version=1.9.24
