import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const styles1 = StyleSheet.create({
  icon71: {
    width: wp('4.8%'),
    height: hp('1.6%'),
  },
  icon711: {
    width: wp('5%'),
    height: hp('2.5%'),

  },
  textInput: {
    flex: 1,
    fontSize: wp('4%'),
    fontFamily: 'Lexend-Regular',
    paddingVertical: hp('1.2%'),
    paddingHorizontal: wp('3%'),
    color: 'black',
  },
  textIn: {
    fontSize: wp('4%'),
    fontFamily: 'Lexend-Regular',
    paddingVertical: hp('1.2%'),
    paddingHorizontal: wp('3%'),
    color: 'black',
  },
  dropdownButton: {
    padding: wp('3%'),
  },
  dropdownIcon: {
    width: wp('5%'),
    height: wp('5%'),
  },
  dropdownContainer: {
    position: 'relative',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: wp('2%'),
    marginTop: hp('1%'),
    zIndex: 1000,
  },
  dropdownItem: {
    padding: wp('3%'),
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  dropdownItemText: {
    fontSize: wp('4%'),
    fontFamily: 'Lexend-Medium',
  },
  eyeOpenStyle: {
    width: wp('5.5%'),
    height: hp('1.8%'),
    marginLeft: -wp('9%'),
  },
  eyeClosedStyle: {
    width: wp('5.5%'),
    height: wp('5.5%'),
    marginLeft: -wp('9%'),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: wp('80%'),
    maxHeight: hp('60%'),
    backgroundColor: '#fff',
    borderRadius: wp('3%'),
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  listItem: {
    width: '100%',
    paddingVertical: hp('1.5%'),
    paddingHorizontal: wp('10%'),
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    alignItems: 'center',
  },
  listItemText: {
    color: '#333',
    fontFamily: 'Lexend-Regular',
    textAlign: 'left',
  },
  closeButton: {
    marginTop: hp('1.2%'),
    fontSize: wp('4%'),
    color: '#FF7E00',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  image: {
    width: '100%',
    height: hp('62%'),
  },
  list: {
    marginVertical: hp('4%'),
  },
  userimage: {
    height: hp('7.5%'),
    width: wp('13%'),
    alignSelf: 'center',
  },
  backimageee: {
    height: hp('13.5%'),
    width: wp('28%'),
    alignSelf: 'center',
  },
  backimage: {
    height: hp('13.5%'),
    width: wp('28%'),
    alignSelf: 'center',
  },
  backimage2: {
    height: hp('9%'),
    width: hp('9%'),
    borderRadius: hp('9%'),
  },
  backimage1: {
    height: hp('2%'),
    width: hp('2%'),
  },
  addimage: {
    height: hp('4%'),
    width: hp('4%'),
    alignSelf: 'center',
    marginTop: -hp('2%'),
  },
  userinfoimage11: {
    height: hp('4%'),
    width: hp('4%'),
  },
  userinfoimage: {
    height: hp('7.5%'),
    width: hp('7.5%'),
  
  },
  userinfoimage1: {
    height: hp('7.5%'),
    width: wp('12%'),
  },
  profileimage: {
    height: hp('7.5%'),
    width: wp('18%'),
  },
  profileimageDM: {
    height: '31%',
    width: '49%',
  },
  profileimageDM1: {
    height: hp('7.5%'),
    width: wp('40%'),
  },
  optionWrapper: {
    flexDirection: 'row',
    marginVertical: hp('1.2%'),
  },
  optionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp('6%'),
    paddingVertical: hp('1.2%'),
    borderRadius: wp('5%'),
    marginRight: wp('2%'),
    borderWidth: 1,
  },
  dot: {
    height: wp('4%'),
    width: wp('4%'),
    borderRadius: wp('2%'),
    marginRight: wp('2%'),
    borderWidth: 1,
    borderColor: '#BFBFBF',
  },
  selectedDot: {
    backgroundColor: '#FF7E00',
    padding: wp('2.5%'),
    borderRadius: wp('30%'),
  },
  optionText: {
    fontSize: wp('3.2%'),
    fontFamily: 'Lexend-Regular',
    color: 'black',
  },
  userimageView: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: wp('30%'),
    marginHorizontal: wp('30%'),
    padding: wp('5%'),
    paddingHorizontal: wp('13%'),
    backgroundColor: '#FDF1E3',
    borderColor: '#FDF1E3',
  },
  NextButtontext: {
    color: '#fff',
    fontSize: wp('4.5%'),
    fontFamily: 'Lexend-Medium',
  },
  tickIcon: {
    width: wp('3.5%'),
    height: wp('3.5%'),
    position: 'absolute',
    left: wp('0.7%'),
    top: hp('0.4%'),
  },
  styletext: {
    color: 'black',
    fontSize: wp('4%'),
    fontFamily: 'Lexend-Regular',
  },
  viewtextinput: {
    borderWidth: 1.5,
    marginTop: hp('1.2%'),
    borderColor: '#E6E6E6',
    borderRadius: wp('2.5%'),
    backgroundColor: 'white',
    alignContent: 'center',
  },
  viewtextinputnumber: {
    borderWidth: 1,
    marginTop: hp('1%'),
    borderColor: '#E6E6E6',
    borderRadius: wp('2.5%'),
    marginHorizontal: wp('5%'),
  },
  textt: {
    color: 'black',
    fontSize: wp('4.5%'),
    fontFamily: 'Lexend-Medium',
    marginTop: hp('3%'),
  },
  textt3: {
    color: 'black',
    fontSize: wp('4.5%'),
    fontFamily: 'Lexend-Regular',
    textAlign: 'center',
    marginTop: hp('1.5%'),
  },
  modaltext3: {
    color: 'black',
    fontSize: wp('4.5%'),
    fontFamily: 'Lexend-Bold',
  },
  textt2: {
    color: 'black',
    fontSize: wp('4.5%'),
    fontFamily: 'Lexend-Regular',
    textAlign: 'center',
  },
  timetext: {
    color: 'black',
    fontSize: wp('4%'),
    fontFamily: 'Lexend-Regular',
    marginTop: hp('2%'),
  },
  inputContainerrr: {
    borderWidth: 1,
    borderRadius: wp('2.5%'),
    marginVertical: hp('0.8%'),
    borderColor: '#ccc',
    backgroundColor: '#fff',
    paddingHorizontal: wp('2.5%'),
    height: hp('5.5%'),
    justifyContent: 'center',
  },
  inputContainer: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: wp('2%'),
    paddingHorizontal: wp('2.5%'),
    height: hp('5%'),
    justifyContent: 'center',
  },
  textInputtt: {
    fontSize: wp('4%'),
    height: hp('5.5%'),
    color: '#000',
    fontFamily: 'Lexend-Regular',
    marginLeft: wp('2.5%'),
  },
  lightcolor: {
    color: '#BFBFBF',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('3.2%'),
  },
  lightcolorB: {
    color: '#BFBFBF',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('3.2%'),
  },
  lightcoB: {
    color: '#BFBFBF',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('4.2%'),
  },
  lightcolorBB: {
    color: '#BFBFBF',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('3.5%'),
    marginLeft: wp('5%'),
  },
  lightcolorB1: {
    color: '#BFBFBF',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('2.8%'),
    alignSelf: 'center',
  },
  lightcolorBB1: {
    color: '#FF7E00',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('3%'),
    marginVertical: hp('2%'),

  },
  lightcolo1: {
    color: '#a6a4a4',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('4%'),
    marginVertical: hp('1%'),
  },
  lightcolor2: {
    color: '#FF7E00',
    fontFamily: 'Lexend-Regular',
    fontSize: wp('3%'),
  },
  dateInputWrapper: {
    flexDirection: 'column',
    marginRight: wp('15%'),
    justifyContent: 'center',
    alignSelf: 'center',
  },
  dateInput: {
    borderWidth: 1,
    borderRadius: wp('2%'),
    height: hp('5.5%'),
    borderColor: '#ccc',
    fontSize: wp('3.5%'),
    color: '#000',
    backgroundColor: '#fff',
    fontFamily: 'Lexend-Regular',
    marginTop: hp('1.2%'),
    padding: wp('3%'),
    alignSelf: 'center',
    paddingLeft: wp('8%'),
    width: wp('90%'),
  },
  dropdownContainerr: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: wp('2%'),
    marginTop: hp('1.2%'),
    paddingHorizontal: wp('2%'),
    backgroundColor: '#fff',
    marginRight: wp('15%'),
  },
  pickerStyle1: {
    height: hp('6%'),
    width: wp('50%'),
    borderWidth: 1,
    borderColor: 'black',
    paddingRight: wp('50%'),
    paddingVertical: hp('3%'),
  },
  Iconquestion: {
    position: 'absolute',
    right: wp('4%'),
    transform: [{ translateY: -5 }],
    height: hp('2.8%'),
    width: hp('2.8%'),
    borderRadius: wp('3%'),
    tintColor: '#BFBFBF',
    top: '50%',
  },
  pickerContainer: {
    borderWidth: 1.2,
    borderColor: '#E6E6E6',
    borderRadius: wp('2%'),
    backgroundColor: '#fff',
    marginRight: wp('2%'),
    paddingHorizontal: wp('2%'),
    justifyContent: 'center',
    width: wp('20%'),
    height: hp('6%'),
    marginTop: hp('0.6%'),
    paddingRight: wp('2%'),
  },
  pickerStyle: {
    position: 'absolute',
  },
  screenContainer: {
    marginHorizontal: wp('5%'),
  },
  backButtonImage: {
    resizeMode: 'stretch',
  },
  profileTouchable: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: wp('30%'),
    marginHorizontal: wp('30%'),
    padding: hp('2.5%'),
    paddingHorizontal: wp('13%'),
    backgroundColor: '#FDF1E3',
    borderColor: '#FDF1E3',
  },
  genderTitle: {
    color: 'black',
    fontSize: wp('4%'),
    fontFamily: 'Lexend-Regular',
    marginTop: hp('4%'),
  },
  continueButton: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: wp('5%'),
    padding: hp('1.2%'),
    marginHorizontal: wp('13%'),
    backgroundColor: '#FF7E00',
    borderColor: '#FF7E00',
    marginTop: hp('10%'),
  },
  continueButtonDisabled: {
    opacity: 0.7,
  },
  dateInputWrapper: {
    flexDirection: 'column',
    marginRight: wp(15),
    justifyContent: 'center',
    alignSelf: 'center',
  },
  dateInput: {
    borderWidth: 1,
    borderRadius: wp(2.4),
    height: hp(5.4),
    borderColor: '#ccc',
    fontSize: wp(3.4),
    color: '#000',
    backgroundColor: '#fff',
    fontFamily: 'Lexend-Regular',
    marginTop: hp(1.2),
    padding: wp(2.4),
    alignSelf: 'center',
    paddingLeft: wp(7.2),
    width: "120%",
  },
  dateInputt: {
    borderWidth: 1,
    borderRadius: wp(2.4),
    height: hp(5.4),
    borderColor: '#ccc',
    fontSize: wp(3.4),
    color: '#000',
    backgroundColor: '#fff',
    fontFamily: 'Lexend-Regular',
    marginTop: hp(1.2),
    width: "130%",
    justifyContent: 'center',
    paddingLeft: wp(7.2),
  },
  dateInputtt: {
    borderWidth: 1,
    borderRadius: wp(2.4),
    height: hp(5.4),
    borderColor: '#ccc',
    fontSize: wp(3.4),
    color: '#000',
    backgroundColor: '#fff',
    fontFamily: 'Lexend-Regular',
    marginTop: hp(1.2),
    justifyContent: 'center',
    width: "130%",
    paddingLeft: wp(4.8),
  },
  dropdownContainer: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: wp(1.9),
    marginTop: hp(1.2),
    paddingHorizontal: wp(1.2),
    backgroundColor: '#fff',
  },
  dropdownContainerr: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: wp(1.9),
    marginTop: hp(1.2),
    paddingHorizontal: wp(1.2),
    backgroundColor: '#fff',
    marginRight: wp(15),
  },
});

export default styles1;
